# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gigitsu
tagline:          'A personal blog'
description:      'A personal blog by <a href="http://gigitsu.github.io" target="_blank">Gigitsu</a>.'
url:              http://gigitsu.github.io
baseurl:          /

author:
  name:           'Luigi Clemente'
  url:            https://twitter.com/Gigitsu23

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Gigitsu/Gigitsu.github.io
